#!/bin/bash

# Build a jar that can serve a site or api
echo "Building space.jar.."
clojure -A:depstar -m hf.depstar.uberjar target/build/space.jar

# Build CLJS for front end
echo "Building space.js.."
clojure -m cljs.main -o target/public/js/space.js -O advanced -c space.site.cljs.core

# Announce that everything has been built
echo "Building successful."
